### ISSUE TITLE
matlib::echelon fails with matrix with single row

### ISSUE THREAD

**Issue by JanaJarecki** [friendly/matlib#30] opened 2020-03-25 17:24 UTC
Hej,
the `matlib::echelon` function cannot handle matrices with one row. While this may be usually not needed at all, I am using the echelon function in a package where it is possible that sometimes the `A` matrix can indeed have one row only. I would prefer the function not to break the code run with an error.

    A <- matrix(c(0,1,1,0), 2)
    b <- 1:2
    matlib::echelon(A,b) # works
    matlib::echelon(A[1, , drop = F],b[1]) #fails
    # should return sth like
    #      [,1] [,2]  [,3]                                                                                    
      [1,]    0    1    1

**Comment by john-d-fox** [comment] 2020-03-25 17:42
Dear Jana,

I agree that echelon() should work for edge cases like a one-row (or one-column) matrix. The problem actually is in gaussianElimination(). I'll look into it when I have a chance.

Thanks for the bug report.

John

**Comment by friendly** [comment] 2020-03-25 19:33
True: the error is triggered in `gaussianElimination`

    > gaussianElimination(A[1, , drop=F], b[1])
    Error in apply(A[, 1:m], 1, function(x) max(abs(x)) <= tol) : 
      dim(X) must have a positive length
    >

**Comment by friendly** [comment] 2020-03-25 19:50
And, there is an arguable case for this in terms of `showEqn` with a simple solution.

    > showEqn(A[1,,drop=F], b[1])
    0*x1 + 1*x2  =  1

**Comment by john-d-fox** [comment] 2020-03-25 20:02
Hi Michael,

I hope that all is well with you, Martha, and the rest of your family. Bonnie and I are back in Toronto, having returned from Florida on Sunday, and of course are in self-isolation. We're fine.

Unless you feel it's urgent and want to fix it yourself, I'll get to this after I finish some other work. I think it should be simple to fix even if just by special-casing one-row and one-column matrices. It would be nice, of course, to have a more elegant solution.

Best,
 John

**Comment by john-d-fox** [comment] 2020-03-26 15:39
Hi,

I think this is now fixed in matlib on GitHub (requiring only two small changes). I also bumped the version number to 0.9.3 and updated the NEWS.md file.

Best,
 John

**Comment by JanaJarecki** [comment] 2020-03-27 17:10
Works like a charm for me

**Comment by john-d-fox** [comment] 2020-03-27 17:27
Dear Jana,

Thanks for check it, and again for the bug report. Michael can decide when we've accumulated enough changes in matlib to justify a new CRAN version.

Best,
 John

**Comment by friendly** [comment] 2020-03-28 03:36
Looks good to me, but I'l have to sort out the devel-0.9-3 branch mentioned in #28

**Comment by john-d-fox** [comment] 2020-03-28 04:01
Hi Michael,

Sorry, I forgot about that. It might be simplest just to revert my changes after you look at what I did to gaussianElimination(), which are just small changes to two lines of code. You could then just apply these changes to the devel branch.

John

**Comment by friendly** [comment] 2020-03-29 20:46
I did some more testing.  `gaussianElimination` and friends work well with 1-row systems. This part seems to be done.

However `plotEqn`  gives an error for equations involving only x1, It does give the correct plot, and the problem has to do with labeling the equation.

    # works for 1-row systems directly

    A1 <- matrix(c(1, 0), nrow=1)
    b1 = 2
    showEqn(A1, b1, simplify=TRUE)
    gaussianElimination(A1, b1)

    # plotEqn give an errors for this case. It gives the right
    # plot, but generates an error
    plotEqn(A1, b1)
    #> plotEqn(A1, b1)
    #x1  =  2 
    #Error in plotEqn(A1, b1) : object 'y' not found
    #>
![image](https://user-images.githubusercontent.com/456353/77860188-c8459000-71db-11ea-9dbe-fcf62c11cf83.png)

    # works for 1-row systems (issue # 30)
    A2 <- matrix(c(1, 1), nrow=1)
    b2 = 2
    gaussianElimination(A2, b2)
    showEqn(A2, b2)
    # plotEqn works for this case
    plotEqn(A2, b2)

![image](https://user-images.githubusercontent.com/456353/77860214-f3c87a80-71db-11ea-9603-17e9f378685b.png)

**Comment by john-d-fox** [comment] 2020-03-29 21:32
Hi Michael,

I made a small change today to gaussianElimination() to make the fix for the one-column case a little more transparent.

Do you want to fix plotEqn() or shall I? I noticed, BTW, that plotEqn() doesn't print proper subscripts for the xs. We could use, e.g., expression(x[1]) to make the labels look nicer.

Best,
 John

**Comment by friendly** [comment] 2020-03-30 15:07
I tried debug() on plotEqn.  I see what the problem is, and fixed it, sort of.

The error occurs for equations of the form x1 = c, i.e., when A[i,2] = 0.  The label for such a line could be positioned at (x=c, y=anywhere).

I modified the code, and it doesn't produce the error.
Can you take a look at the latest commit?

My test case is:

    A1 <- matrix(c(1, 0), nrow=1)
    b1 = 2
    showEqn(A1, b1, simplify=TRUE)
    plotEqn(A1, b1)

This gives

![image](https://user-images.githubusercontent.com/456353/77928557-903f5b00-7276-11ea-8893-6fd4a7e9552e.png)

**Comment by john-d-fox** [comment] 2020-03-30 15:57
Hi,

> -----Original Message-----
> From: Michael Friendly <notifications@github.com>
> Sent: Monday, March 30, 2020 11:08 AM
> To: friendly/matlib <matlib@noreply.github.com>
> Cc: Fox, John <jfox@mcmaster.ca>; Comment <comment@noreply.github.com>
> Subject: Re: [friendly/matlib] matlib::echelon fails with matrix with
> single row (#30)
> 
> I tried debug() on plotEqn. I see what the problem is, and fixed it, sort
> of.
> 
> The error occurs for equations of the form x1 = c, i.e., when A[i,2] = 0.
> The label for such a line could be positioned at (x=c, y=anywhere).
> 
> I modified the code, and it doesn't produce the error.
> Can you take a look at the latest commit?

Sure. I should be able to get to this later today.

Should I also try to improve the typesetting of the labels?

John

**Comment by john-d-fox** [comment] 2020-03-30 18:10
Hi,

This looks right to me. I also pushed a change to the default labelling so that subscripts are properly typeset. You can revert it if you don't like it.

That just leaves the hex sticker question ;)

John

**Comment by friendly** [comment] 2020-03-30 18:57
Great! Let's call this done.

If there are no further changes, I'll begin to roll out the current version to CRAN.

**Closed as completed** 2020-03-31 16:37 UTC
